### PR TITLE
[CORE-59] - Reduce canvaskit.wasm size

### PR DESCRIPTION
**Pull request by mmogilnitsky**
Reduce CanvasKit.wasm size by enabling only the needed pices.
Make a package.json ready for  for submission.

CORE-59

### CODE REVIEW

**Comment by leoyanggit** [comment]
I'm not sure the branching strategy here. If we land this onto the master but we want to have a custom build that is based on a specific SHA that corresponds to an upstream CanvasKit release, what would we do? Branching off from the SHA and cherry-pick this patch?

**Comment by mmogilnitsky** [comment]
WSL-2 maximm-49YPY33:~/dev/skia cmp2 $ git remote -v
origin  git@github.com:Bluescape/skia.git (fetch)
origin  git@github.com:Bluescape/skia.git (push)
upstream        https://github.com/google/skia.git (fetch)
upstream        https://github.com/google/skia.git (push)

Rather simple @leoyanggit 
We fork from google/skia - upsteam
The we work on our branch - origin
Once we decide to update skia
We do sync to upstream branch 
And merge it 
Obviously diffs to be resolve.

**Comment by leoyanggit** [comment]
> WSL-2 maximm-49YPY33:~/dev/skia cmp2 $ git remote -v
> origin [git@github.com](mailto:git@github.com):Bluescape/skia.git (fetch)
> origin [git@github.com](mailto:git@github.com):Bluescape/skia.git (push)
> upstream https://github.com/google/skia.git (fetch)
> upstream https://github.com/google/skia.git (push)
> 
> Rather simple @leoyanggit
> We fork from google/skia - upsteam
> The we work on our branch - origin
> Once we decide to update skia
> We do sync to upstream branch
> And merge it

Using `git merge` and creating a merge commit on `origin/master`?

> Obviously diffs to be resolve.

**Comment by mmogilnitsky** [comment]
Yes @leoyanggit

**Comment by leoyanggit** [comment]
> Yes @leoyanggit

That means we will create merge commit that makes it hard to track history.

**Comment by mmogilnitsky** [comment]
In bad case scenario you are right @leoyanggit 
But we need to choose something.
And it's better to be traceable.
So I just followed what everybody else does.

**Review by ja2nicholl — APPROVED** [review]

**Pull request merged**
